### ISSUE TITLE
(facility_management.facility_management.doctype.real_estate_property.real_estate_property Error: No module named 'toolz')

### ISSUE THREAD

**Issue by jamesvrempel** [iRaySpace/facility_management#10]
Installing facility_management...
Updating DocTypes for facility_management: [=========                               ]An error occurred while installing facility_management:
Module import failed for Real Estate Property (facility_management.facility_management.doctype.real_estate_property.real_estate_property Error: No module named 'toolz')

Have tried the recent update with toolz 0.9.0 installed.  The environment is ERPNext 12.21.0.  Cheers.  James.

**Comment by iRaySpace** [comment]
Hello,

Try the following commands
```
cd frappe-bench
source env/bin/activate
pip install toolz==0.9.0
```

Regards,

Ivan

**Comment by jamesvrempel** [comment]
Thanks for that - it has worked.  Cheers.  James.

James Rempel 
Operations

Enterprise Systems Australia
A: Suite 19 50 St Georges Tce Perth Western Australia 6000 
E: ***@***.***  
M: +61 409 680 967 
W: https://enterprisesystems.com.au




On 4 Jun 2021, at 9:41 pm, Ivan Ray Altomera ***@***.***> wrote:


Hello,

Try the following commands

cd frappe-bench
source env/bin/activate
pip install toolz==0.9.0
Regards,

Ivan
