### ISSUE TITLE
(facility_management.facility_management.doctype.real_estate_property.real_estate_property Error: No module named 'toolz')

### ISSUE THREAD

**Issue by jamesvrempel** [iRaySpace/facility_management#9]
Installing facility_management...
Updating DocTypes for facility_management: [=========                               ]An error occurred while installing facility_management:
Module import failed for Real Estate Property (facility_management.facility_management.doctype.real_estate_property.real_estate_property Error: No module named 'toolz')

**Comment by iRaySpace** [comment]
Hello,

I added `toolz` on `requirements.txt`. Pull and install the app again.

Thanks,

Ivan
